version: '3'

services:

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    volumes: # data to map to the container
      #- ../src/DB:/docker-entrypoint-initdb.d # where to find the db dump data
      - wordpress_db_data:/var/lib/mysql
    restart: unless-stopped
    environment: # mysql options
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    # for mysql 8.0, change autentication to native password (legacy)
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  wordpress:
    container_name: ${APP_NAME}-wordpress
    depends_on:
      - db
    build:
      context: ./images/wordpress
      args:
        - SERVER_NAME=${APP_NAME}.local
      dockerfile: Dockerfile # need to install the wp-cli that is missing from the official image
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:${MYSQL_PORT}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD} # matches the password set in the db container
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DEBUG=true
    extra_hosts:
     - "${APP_NAME}.local:127.0.0.1"
    hostname: ${APP_NAME}.local
    domainname: local 
    volumes:
      - ../src:/var/www/html:cached

#    nginx:
#      image: nginx:latest
#      volumes:
 #       - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
 #       - "./nginx/ssl/my_wpress_site.cert:/etc/nginx/my_wpress_site.cert"
 #       - "./nginx/ssl/my_wpress_site.key:/etc/nginx/my_wpress_site.key"
 #       - "/var/log/nginx:/var/log/nginx"
 #     ports:
 #       - "80:80"
 #       - "443:443"
  #    depends_on:
 #       - wordpress
 #     links:
 #       - wordpress
 #     restart: unless-stopped
 #     container_name: wp_nginx

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}-phpmyadmin"
    restart: unless-stopped
    environment:
      PMA_HOST: db:${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80
  
  mailcatcher:
    image: sj26/mailcatcher
    container_name: "${APP_NAME}-mailcatcher"
    ports:
      - "1080:1080"

volumes:
  wordpress_db_data: {} # persist db data in native named volume
